name: Windows 11 RDP VM + Auto Tailscale

on:
  workflow_dispatch:
    inputs:
      hostname:
        description: 'Tailscale hostname'
        required: false
        default: rdp-windows

jobs:
  deploy-windows-vm:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests || true

      - name: Generate random credentials
        id: creds
        run: |
          import secrets, string, random
          user = 'user' + ''.join(random.choices(string.ascii_lowercase + string.digits, k=8))
          pw = ''.join(secrets.choice(string.ascii_letters + string.digits + '!@#$%&*') for _ in range(16))
          with open('rdp-credentials.txt', 'w') as f:
              f.write(f'USER={user}\nPASS={pw}\nIP=0.0.0.0\n')
          print(f"::set-output name=user::{user}")
          print(f"::set-output name=pass::{pw}")
        shell: python

      - name: Deploy Windows 11 VM on Vast.ai
        run: python deploy_windows_vm_tailscale.py
        env:
          VAST_API_KEY: ${{ secrets.VAST_API_KEY }}
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
          HOSTNAME: ${{ github.event.inputs.hostname }}

      - name: Show generated credentials
        run: |
          cat rdp-credentials.txt

      - name: Upload RDP credentials artifact
        uses: actions/upload-artifact@v4
        with:
          name: rdp-credentials
          path: rdp-credentials.txt
          
